import { describe, expect, it } from 'vitest';
import { apigw006Control } from '../../../../../../../src/assess/scanning/security-matrix/rules/api-gateway/apigw-006/apigw-006.control.js';
import { Apigw006TfAdapterFactory } from '../../../../../../../src/assess/scanning/security-matrix/rules/api-gateway/apigw-006/apigw-006.adapter.tf.js';
import type { Apigw006Adapter } from '../../../../../../../src/assess/scanning/security-matrix/rules/api-gateway/apigw-006/apigw-006.adapter.js';
import type { ScanResult, TerraformResource, TfContext } from '../../../../../../../src/assess/scanning/security-matrix/controls/types.js';

const factory = new Apigw006TfAdapterFactory();

const stage: TerraformResource = {
  type: 'aws_api_gateway_stage',
  name: 'prod',
  address: 'aws_api_gateway_stage.prod',
  values: {
    stage_name: 'prod',
    rest_api_id: 'aws_api_gateway_rest_api.api',
  },
} as unknown as TerraformResource;

function methodSettings(values: Record<string, unknown>): TerraformResource {
  return {
    type: 'aws_api_gateway_method_settings',
    name: 'all',
    address: 'aws_api_gateway_method_settings.all',
    values: {
      // reference form: stage_name = aws_api_gateway_stage.prod.stage_name
      stage_name: 'aws_api_gateway_stage.prod',
      rest_api_id: 'aws_api_gateway_rest_api.api',
      method_path: '*/*',
      ...values,
    },
  } as unknown as TerraformResource;
}

function scan(resources: TerraformResource[]): ScanResult | null {
  const allResources = [stage, ...resources];
  const context: TfContext = {
    projectName: 'test-project',
    resource: stage,
    allResources,
  };
  const adapter: Apigw006Adapter = factory.bind(context) as Apigw006Adapter;
  return apigw006Control.run(adapter, context);
}

describe('APIGW-006 REQ-13 (Terraform) — undeterminable method settings pass', () => {
  // Primary behaviour owned by this requirement: undeterminable => pass.
  it('passes when the logging level of the catch-all method settings is unknown at plan time', () => {
    const result = scan([
      methodSettings({ settings: [{ logging_level: null, metrics_enabled: true }] }),
    ]);

    expect(result).toBeNull();
  });

  it('passes when the settings block itself is generated by an unresolved conditional expression', () => {
    const result = scan([
      methodSettings({ settings: null }),
    ]);

    expect(result).toBeNull();
  });

  it('passes when the method path targeted by the settings is unknown at plan time', () => {
    const result = scan([
      methodSettings({ method_path: null, settings: [{ logging_level: 'INFO' }] }),
    ]);

    expect(result).toBeNull();
  });

  // Opposite outcome: same reference-form settings, but a determinable, non-accepted logging level.
  it('flags catch-all method settings whose logging level resolves to a non-accepted value', () => {
    const result = scan([
      methodSettings({ settings: [{ logging_level: 'OFF', metrics_enabled: true }] }),
    ]);

    expect(result).not.toBeNull();
    expect(result?.check_id).toBe('APIGW-006');
  });
});
